name: Check C++ format

on:
  - push

jobs:
  check:
    env:
        TZ: Europe/Zurich
        DEBIAN_FRONTEND: noninteractive
    runs-on: ubuntu-20.04
    steps:
      - name: apt
        run: |
          sudo apt install -y --no-install-recommends clang-format-12
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout master
        run: git fetch --no-tags --depth=1 origin +refs/heads/master:refs/heads/master
      - name: clang-format
        run: clang-format -i --style=file `find src include domain -type f`
        # run: ./.github/scripts/clang-format.sh
      - name: report formating issues (if any)
        if: always()
        run: git diff --color --exit-code
